# Generated by Django 5.2 on 2025-05-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_level_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shortdescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_modules',
            field=models.IntegerField(default=0),
        ),
    ]
