# Generated by Django 5.2 on 2025-05-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_instructor_course_instructor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
    ]
