# Generated by Django 5.2 on 2025-05-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_category_id_course_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='instructor_id',
        ),
    ]
