# Generated by Django 5.2 on 2025-05-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_category_course_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subcategory',
            new_name='subcategory_id',
        ),
    ]
