# Generated by Django 5.2 on 2025-06-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('deleted', 'deleted')], default='archived', max_length=10),
        ),
    ]
