# Generated by Django 5.2 on 2025-05-17 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodules', '0002_rename_id_coursemodule_module_id'),
        ('lessons', '0002_alter_lesson_content_type_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='coursemodule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='coursemodules.coursemodule'),
        ),
    ]
