# Generated by Django 5.2 on 2025-07-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_admin_user_id'),
        ('categories', '0002_alter_category_status'),
        ('courses', '0003_course_shortdescription_course_total_modules'),
        ('instructors', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='instructor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_instructor', to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_admin', to='admins.admin'),
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='applicable_categories',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='applicable_courses',
        ),
        migrations.AddField(
            model_name='promotion',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='categories.category'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applicable_courses',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='courses.course'),
        ),
    ]
