# Generated by Django 5.2 on 2025-05-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemodules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodule',
            old_name='id',
            new_name='module_id',
        ),
    ]
