# Generated by Django 5.2 on 2025-07-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_details',
            old_name='primotion_id',
            new_name='promotion_id',
        ),
    ]
