# Generated by Django 5.2 on 2025-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_admin_user_alter_admin_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
