# Generated by Django 5.2 on 2025-05-21 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_level_alter_course_status'),
        ('promotions', '0001_initial'),
        ('users', '0002_alter_user_status_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_course', to='courses.course')),
                ('promotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_promotion', to='promotions.promotion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to='users.user')),
            ],
            options={
                'db_table': 'Cart',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'course_id'), name='unique_cart')],
            },
        ),
    ]
