# Generated by Django 5.2 on 2025-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
