# Generated by Django 5.2 on 2025-05-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
