# Generated by Django 5.2 on 2025-07-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='refund_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refund_reason',
        ),
    ]
