# Generated by Django 5.2 on 2025-05-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='user',
            new_name='user_id',
        ),
    ]
