# Generated by Django 5.2 on 2025-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple', 'multiple'), ('truefalse', 'true/false'), ('short', 'short'), ('essay', 'Essay')], max_length=20),
        ),
    ]
