# Generated by Django 5.2 on 2025-05-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_questions', '0002_alter_quizquestion_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='user_id',
        ),
    ]
